### ISSUE TITLE
Add color legend to node graphs

### ISSUE THREAD

**Issue by maximusunc** [RobokopU24/qgraph#182]
Right now, we color nodes based on their categories. It would be nice to show the user a legend key that matches a color with a category.

**Comment by karafecho** [comment]
Agreed. I just ran a query that returned a node in a dark red color that I had never seen before. I had to ask David to look it up for me. Would be much easier to have a legend on the question-builder page.

**Comment by karafecho** [comment]
This issue has been addressed, so closing ticket ...
