### ISSUE TITLE
Finish converting qgraph to ROBOKOP?

### ISSUE THREAD

**Issue by maximusunc** [RobokopU24/qgraph#256]
The qgraph.org domain registration will expire in 30 days. Do we want to renew, or move the UI back over to a robokop.renci.org domain?

I also noticed that the Auth0 sign-in still says qgraph. I can update that, or I think Evan has access. Do we want to update it?

**Comment by cbizon** [comment]
We're working on reforming all the URLs so we'll have it under robokop.renci.org/questionbuilder or something similar.  So I think we can let the domain expire unless you want it for your own purposes...

**Comment by cbizon** [comment]
What's the Auth0 for @maximusunc ?
