### ISSUE TITLE
Display node CURIE and/or URL/metadata

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/qgraph#261]
At present, users cannot see node CURIEs or Biolink categories without digging through the result JSON. This issue is to suggest adding a new feature that would allow users to be able to click or hover over a node and see the CURIE, e.g., HP:0012042, and/or the URL, e.g., https://hpo.jax.org/app/browse/term/HP:0012042. If I recall, the prior version of ROBOKOP supported this feature. Might be good to add this back.

**Comment by Woozl** [comment]
closed by #262
